cd C:\KUGCP2CSV\KUGCP2CSV
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_PTBASE.sql C:\KUGCP2CSV\csv\MDV_PTBASE.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_PTPROFILE.sql C:\KUGCP2CSV\csv\MDV_PTPROFILE.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_DISEASE.sql C:\KUGCP2CSV\csv\MDV_DISEASE.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_BOOK.sql C:\KUGCP2CSV\csv\MDV_BOOKE.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_ADMIT_RESERVATION.sql C:\KUGCP2CSV\csv\MDV_ADMIT_RESERVATION.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_ADMIT.sql C:\KUGCP2CSV\csv\MDV_ADMIT.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_SAMPLE_RSLT.sql C:\KUGCP2CSV\csv\MDV_SAMPLE_RSLT.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_SOMATOMETRY.sql C:\KUGCP2CSV\csv\MDV_SOMATOMETRY.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_NSDB_GN.sql C:\KUGCP2CSV\csv\MDV_NSDB_GN.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_DRUG.sql C:\KUGCP2CSV\csv\MDV_DRUG.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_INJECTION.sql C:\KUGCP2CSV\csv\MDV_INJECTION.csv
python BQOutPutCSV.py C:\KUGCP2CSV\SQL\SQL_MDV_PATHOLOGY.sql C:\KUGCP2CSV\csv\MDV_PATHOLOGY.csv